//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.832
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiPRipper {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiPRipper.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System is extracting... ähnelt.
        /// </summary>
        internal static string bSystemExtr {
            get {
                return ResourceManager.GetString("bSystemExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RiP-Ripper finished all Downloads ähnelt.
        /// </summary>
        internal static string btexExit {
            get {
                return ResourceManager.GetString("btexExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloads Complete ähnelt.
        /// </summary>
        internal static string btleExit {
            get {
                return ResourceManager.GetString("btleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System is idling ähnelt.
        /// </summary>
        internal static string btleIdle {
            get {
                return ResourceManager.GetString("btleIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide Picture --&gt; ähnelt.
        /// </summary>
        internal static string btnHidePicture {
            get {
                return ResourceManager.GetString("btnHidePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Folder ähnelt.
        /// </summary>
        internal static string btnOpenFolder {
            get {
                return ResourceManager.GetString("btnOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Picture --&gt; ähnelt.
        /// </summary>
        internal static string btnShowPicture {
            get {
                return ResourceManager.GetString("btnShowPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start Download ähnelt.
        /// </summary>
        internal static string btnStartDownload {
            get {
                return ResourceManager.GetString("btnStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop Download ähnelt.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always on Top ähnelt.
        /// </summary>
        internal static string chbAlwaysOnTop {
            get {
                return ResourceManager.GetString("chbAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ask For Download Folder before Downloading ähnelt.
        /// </summary>
        internal static string chbAskDownloadFolder {
            get {
                return ResourceManager.GetString("chbAskDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically press the &quot;Thank You&quot; Button ähnelt.
        /// </summary>
        internal static string chbAutoTKButton {
            get {
                return ResourceManager.GetString("chbAutoTKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Ripped posts for checking ähnelt.
        /// </summary>
        internal static string chbSaveHistory {
            get {
                return ResourceManager.GetString("chbSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show &quot;Downloads Complete&quot; PopUp? ähnelt.
        /// </summary>
        internal static string chbShowDCPopUps {
            get {
                return ResourceManager.GetString("chbShowDCPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Tray PopUps ähnelt.
        /// </summary>
        internal static string chbShowPopUps {
            get {
                return ResourceManager.GetString("chbShowPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Subdirectories for new Downloads ähnelt.
        /// </summary>
        internal static string chbSubdirectories {
            get {
                return ResourceManager.GetString("chbSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download each post in its own folder ähnelt.
        /// </summary>
        internal static string chbSubThreadRip {
            get {
                return ResourceManager.GetString("chbSubThreadRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember Me ähnelt.
        /// </summary>
        internal static string chRememberCred {
            get {
                return ResourceManager.GetString("chRememberCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extracting ähnelt.
        /// </summary>
        internal static string CurrentlyExtract {
            get {
                return ResourceManager.GetString("CurrentlyExtract", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Options ähnelt.
        /// </summary>
        internal static string downloadOptions {
            get {
                return ResourceManager.GetString("downloadOptions", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap fr {
            get {
                object obj = ResourceManager.GetObject("fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently, ähnelt.
        /// </summary>
        internal static string gbCurrently {
            get {
                return ResourceManager.GetString("gbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently, System is waiting for threads to exit... ähnelt.
        /// </summary>
        internal static string gbCurrentlyExit {
            get {
                return ResourceManager.GetString("gbCurrentlyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently, System is extracting:  ähnelt.
        /// </summary>
        internal static string gbCurrentlyExtract {
            get {
                return ResourceManager.GetString("gbCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Currently, System is idling... ähnelt.
        /// </summary>
        internal static string gbCurrentlyIdle {
            get {
                return ResourceManager.GetString("gbCurrentlyIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Language ähnelt.
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Provide Login Credentials to RiP Forums ähnelt.
        /// </summary>
        internal static string gbLoginHead {
            get {
                return ResourceManager.GetString("gbLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Options ähnelt.
        /// </summary>
        internal static string gbMainOptions {
            get {
                return ResourceManager.GetString("gbMainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parsing Cached Thread XML... ähnelt.
        /// </summary>
        internal static string gbParse {
            get {
                return ResourceManager.GetString("gbParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Folder : ähnelt.
        /// </summary>
        internal static string lblDownloadFolder {
            get {
                return ResourceManager.GetString("lblDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading: 0 of 0 ähnelt.
        /// </summary>
        internal static string lblDownloading {
            get {
                return ResourceManager.GetString("lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloading: {0} of {1} ähnelt.
        /// </summary>
        internal static string lblDownloadingof {
            get {
                return ResourceManager.GetString("lblDownloadingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login FAILED! ähnelt.
        /// </summary>
        internal static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Picture Downloaded: ähnelt.
        /// </summary>
        internal static string lblLastPicture {
            get {
                return ResourceManager.GetString("lblLastPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. Image Count to give Thanks: ähnelt.
        /// </summary>
        internal static string lblminImageCount {
            get {
                return ResourceManager.GetString("lblminImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password : ähnelt.
        /// </summary>
        internal static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ripping Queue ähnelt.
        /// </summary>
        internal static string lblRippingQue {
            get {
                return ResourceManager.GetString("lblRippingQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for RiP-Productions... ähnelt.
        /// </summary>
        internal static string lblStatWait {
            get {
                return ResourceManager.GetString("lblStatWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thread Limit: ähnelt.
        /// </summary>
        internal static string lblThreadLimit {
            get {
                return ResourceManager.GetString("lblThreadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads: {0} of {1} ähnelt.
        /// </summary>
        internal static string lblThreads {
            get {
                return ResourceManager.GetString("lblThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads: 0 of  ähnelt.
        /// </summary>
        internal static string lblThreads2 {
            get {
                return ResourceManager.GetString("lblThreads2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Name : ähnelt.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNING! More than 3 failed tries will result in your RiP Account being locked! You have been warned! ähnelt.
        /// </summary>
        internal static string lblWarningLogin {
            get {
                return ResourceManager.GetString("lblWarningLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome,  ähnelt.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string logintext {
            get {
                return ResourceManager.GetString("logintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die That Thread or Post is Already Queued for RIP ähnelt.
        /// </summary>
        internal static string mbAlreadyQueued {
            get {
                return ResourceManager.GetString("mbAlreadyQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You entered an incorrect URL. ähnelt.
        /// </summary>
        internal static string mbIncorrectURL {
            get {
                return ResourceManager.GetString("mbIncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Destination Path! Please set up the Download Folder first. ähnelt.
        /// </summary>
        internal static string mbInvalidDes {
            get {
                return ResourceManager.GetString("mbInvalidDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No such post exists! ähnelt.
        /// </summary>
        internal static string mbNoPost {
            get {
                return ResourceManager.GetString("mbNoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No such thread exists! ähnelt.
        /// </summary>
        internal static string mbNoThread {
            get {
                return ResourceManager.GetString("mbNoThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Min. Image Count to give Thanks&quot;, must be a numeric value! ähnelt.
        /// </summary>
        internal static string mbNum {
            get {
                return ResourceManager.GetString("mbNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thread Limit MUST be between 1 and 20! ähnelt.
        /// </summary>
        internal static string mbThreadbetw {
            get {
                return ResourceManager.GetString("mbThreadbetw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thread Limit MUST be numeric! ähnelt.
        /// </summary>
        internal static string mbThreadNum {
            get {
                return ResourceManager.GetString("mbThreadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID MUST be numeric! ähnelt.
        /// </summary>
        internal static string mbTNumeric {
            get {
                return ResourceManager.GetString("mbTNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version of Ripper is available. You should upgrade at your earliest convenience. To upgrade head to: www.watchersnet.de/rip-ripper ähnelt.
        /// </summary>
        internal static string mbUpdate {
            get {
                return ResourceManager.GetString("mbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Version Available! ähnelt.
        /// </summary>
        internal static string mbUpdate2 {
            get {
                return ResourceManager.GetString("mbUpdate2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Images remaining (Total Downloaded: {1}%) ähnelt.
        /// </summary>
        internal static string tiImagesRemain {
            get {
                return ResourceManager.GetString("tiImagesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RiPRipper Downloading ... ähnelt.
        /// </summary>
        internal static string tthisText {
            get {
                return ResourceManager.GetString("tthisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  [Logged in as: &quot; ähnelt.
        /// </summary>
        internal static string ttlHeader {
            get {
                return ResourceManager.GetString("ttlHeader", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
