//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiPRipper.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class german {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal german() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RiPRipper.Languages.german", typeof(german).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System extrahiert....
        /// </summary>
        internal static string bSystemExtr {
            get {
                return ResourceManager.GetString("bSystemExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG-Ripper hat alle Downloads abgeschlossen.
        /// </summary>
        internal static string btexExit {
            get {
                return ResourceManager.GetString("btexExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads abgeschlossen.
        /// </summary>
        internal static string btleExit {
            get {
                return ResourceManager.GetString("btleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das System faulenzt.
        /// </summary>
        internal static string btleIdle {
            get {
                return ResourceManager.GetString("btleIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übernehmen.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordner öffen.
        /// </summary>
        internal static string btnOpenFolder {
            get {
                return ResourceManager.GetString("btnOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte Download.
        /// </summary>
        internal static string btnStartDownload {
            get {
                return ResourceManager.GetString("btnStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job stoppen/löschen.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrahierung.
        /// </summary>
        internal static string bttleCurrentlyExtract {
            get {
                return ResourceManager.GetString("bttleCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenster immer im Vordergrund.
        /// </summary>
        internal static string chbAlwaysOnTop {
            get {
                return ResourceManager.GetString("chbAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nach Download Ordner fragen bevor der Download startet.
        /// </summary>
        internal static string chbAskDownloadFolder {
            get {
                return ResourceManager.GetString("chbAskDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatisch den &quot;Thank You&quot; Button drücken.
        /// </summary>
        internal static string chbAutoTKButton {
            get {
                return ResourceManager.GetString("chbAutoTKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerippte Beiträge speichern zum checken.
        /// </summary>
        internal static string chbSaveHistory {
            get {
                return ResourceManager.GetString("chbSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige &quot;Downloads abgeschlossen&quot; PopUp?.
        /// </summary>
        internal static string chbShowDCPopUps {
            get {
                return ResourceManager.GetString("chbShowDCPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray PopUps benutzen.
        /// </summary>
        internal static string chbShowPopUps {
            get {
                return ResourceManager.GetString("chbShowPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themen in Unterverzeichnisse herunterladen.
        /// </summary>
        internal static string chbSubdirectories {
            get {
                return ResourceManager.GetString("chbSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beiträge in Unterverzeichnisse herunterladen.
        /// </summary>
        internal static string chbSubThreadRip {
            get {
                return ResourceManager.GetString("chbSubThreadRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung speichern.
        /// </summary>
        internal static string chRememberCred {
            get {
                return ResourceManager.GetString("chRememberCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Optionen.
        /// </summary>
        internal static string downloadOptions {
            get {
                return ResourceManager.GetString("downloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell,.
        /// </summary>
        internal static string gbCurrently {
            get {
                return ResourceManager.GetString("gbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell, Wartet das System auf das Beenden von Threads....
        /// </summary>
        internal static string gbCurrentlyExit {
            get {
                return ResourceManager.GetString("gbCurrentlyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell, extrahiert das System.
        /// </summary>
        internal static string gbCurrentlyExtract {
            get {
                return ResourceManager.GetString("gbCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuell, faulenzt das System....
        /// </summary>
        internal static string gbCurrentlyIdle {
            get {
                return ResourceManager.GetString("gbCurrentlyIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oder als Gast anmelden ....
        /// </summary>
        internal static string gbGuestLoginHead {
            get {
                return ResourceManager.GetString("gbGuestLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachauswahl.
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geben Sie ihere Zugangsdaten aus dem Forum ein.
        /// </summary>
        internal static string gbLoginHead {
            get {
                return ResourceManager.GetString("gbLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programm Optionen.
        /// </summary>
        internal static string gbMainOptions {
            get {
                return ResourceManager.GetString("gbMainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysiert das gecachte XML....
        /// </summary>
        internal static string gbParse {
            get {
                return ResourceManager.GetString("gbParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysiert die jobs.xml....
        /// </summary>
        internal static string gbParse2 {
            get {
                return ResourceManager.GetString("gbParse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als Gast anmelden.
        /// </summary>
        internal static string guestLoginButton {
            get {
                return ResourceManager.GetString("guestLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [Gast Modus].
        /// </summary>
        internal static string guestModeText {
            get {
                return ResourceManager.GetString("guestModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Ordner :.
        /// </summary>
        internal static string lblDownloadFolder {
            get {
                return ResourceManager.GetString("lblDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lädt: 0 von 0.
        /// </summary>
        internal static string lblDownloading {
            get {
                return ResourceManager.GetString("lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lädt: {0} von {1}.
        /// </summary>
        internal static string lblDownloadingof {
            get {
                return ResourceManager.GetString("lblDownloadingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmeldung FEHLGESCHLAGEN!.
        /// </summary>
        internal static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuletzt heruntergeladenens Bild:.
        /// </summary>
        internal static string lblLastPicture {
            get {
                return ResourceManager.GetString("lblLastPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Anzahl an Bildern für Thanks:.
        /// </summary>
        internal static string lblminImageCount {
            get {
                return ResourceManager.GetString("lblminImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort :.
        /// </summary>
        internal static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausstehende Jobs.
        /// </summary>
        internal static string lblRippingQue {
            get {
                return ResourceManager.GetString("lblRippingQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warte auf Forum....
        /// </summary>
        internal static string lblStatWait {
            get {
                return ResourceManager.GetString("lblStatWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale Gleichzeitige Downloads:.
        /// </summary>
        internal static string lblThreadLimit {
            get {
                return ResourceManager.GetString("lblThreadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads: {0} von {1}.
        /// </summary>
        internal static string lblThreads {
            get {
                return ResourceManager.GetString("lblThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads: 0 von .
        /// </summary>
        internal static string lblThreads2 {
            get {
                return ResourceManager.GetString("lblThreads2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername :.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNUNG! Mehr als 3 fehlgeschlagenden versuche, und ihr Account wird gesperrt! Sie wurden also gewarnt!.
        /// </summary>
        internal static string lblWarningLogin {
            get {
                return ResourceManager.GetString("lblWarningLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen, .
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        internal static string logintext {
            get {
                return ResourceManager.GetString("logintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beitag wurde bereits gerippet, Wollen Sie den Beitrag erneut rippen?.
        /// </summary>
        internal static string mBAlready {
            get {
                return ResourceManager.GetString("mBAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Thema oder Beitrag wird bereits geladen!.
        /// </summary>
        internal static string mbAlreadyQueued {
            get {
                return ResourceManager.GetString("mbAlreadyQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie den Ripper beenden?.
        /// </summary>
        internal static string mbExit {
            get {
                return ResourceManager.GetString("mbExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripper beenden.
        /// </summary>
        internal static string mbExitTtl {
            get {
                return ResourceManager.GetString("mbExitTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben eine ungültige URL eingegeben!..
        /// </summary>
        internal static string mbIncorrectURL {
            get {
                return ResourceManager.GetString("mbIncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Ziel Verzeichnis! Bitte geben Sie zuerst ein Download Verzeichnis an!.
        /// </summary>
        internal static string mbInvalidDes {
            get {
                return ResourceManager.GetString("mbInvalidDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Beitrag exestiert nicht!.
        /// </summary>
        internal static string mbNoPost {
            get {
                return ResourceManager.GetString("mbNoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieses Thema exestiert nicht!.
        /// </summary>
        internal static string mbNoThread {
            get {
                return ResourceManager.GetString("mbNoThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit MUSS zwischen 1 und 20 liegen!.
        /// </summary>
        internal static string mbThreadbetw {
            get {
                return ResourceManager.GetString("mbThreadbetw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit MUSS numerisch sein!.
        /// </summary>
        internal static string mbThreadNum {
            get {
                return ResourceManager.GetString("mbThreadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID MUSS eine Nummer sein!.
        /// </summary>
        internal static string mbTNumeric {
            get {
                return ResourceManager.GetString("mbTNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine neue Version vom Ripper ist verfügbar. Möchten Sie das Programm aktualisieren?.
        /// </summary>
        internal static string mbUpdate {
            get {
                return ResourceManager.GetString("mbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Version ist verfügbar!.
        /// </summary>
        internal static string mbUpdate2 {
            get {
                return ResourceManager.GetString("mbUpdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Über.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! Warte auf das beenden von Downloads....
        /// </summary>
        internal static string StatusLabelInfo {
            get {
                return ResourceManager.GetString("StatusLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Bilder verbleiben (Insgesamt geladen: {1}%) .
        /// </summary>
        internal static string tiImagesRemain {
            get {
                return ResourceManager.GetString("tiImagesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VG-Ripper lädt ....
        /// </summary>
        internal static string tthisText {
            get {
                return ResourceManager.GetString("tthisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  [Angemeldet als: &quot;.
        /// </summary>
        internal static string ttlHeader {
            get {
                return ResourceManager.GetString("ttlHeader", resourceCulture);
            }
        }
    }
}
