//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripper.Languages {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class english {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal english() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ripper.Languages.english", typeof(english).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 After Download(s) finished... 的本地化字符串。
        /// </summary>
        internal static string AfterDownload {
            get {
                return ResourceManager.GetString("AfterDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap App1 {
            get {
                object obj = ResourceManager.GetObject("App1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 System is extracting... 的本地化字符串。
        /// </summary>
        internal static string bSystemExtr {
            get {
                return ResourceManager.GetString("bSystemExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VG-Ripper finished all Downloads 的本地化字符串。
        /// </summary>
        internal static string btexExit {
            get {
                return ResourceManager.GetString("btexExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloads Complete 的本地化字符串。
        /// </summary>
        internal static string btleExit {
            get {
                return ResourceManager.GetString("btleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System is idling 的本地化字符串。
        /// </summary>
        internal static string btleIdle {
            get {
                return ResourceManager.GetString("btleIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Folder 的本地化字符串。
        /// </summary>
        internal static string btnOpenFolder {
            get {
                return ResourceManager.GetString("btnOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Download 的本地化字符串。
        /// </summary>
        internal static string btnStartDownload {
            get {
                return ResourceManager.GetString("btnStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop/Delete Job 的本地化字符串。
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on Top 的本地化字符串。
        /// </summary>
        internal static string chbAlwaysOnTop {
            get {
                return ResourceManager.GetString("chbAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ask For Download Folder before Downloading 的本地化字符串。
        /// </summary>
        internal static string chbAskDownloadFolder {
            get {
                return ResourceManager.GetString("chbAskDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically press the &quot;Thank You&quot; Button 的本地化字符串。
        /// </summary>
        internal static string chbAutoTKButton {
            get {
                return ResourceManager.GetString("chbAutoTKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Ripped posts for checking 的本地化字符串。
        /// </summary>
        internal static string chbSaveHistory {
            get {
                return ResourceManager.GetString("chbSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show &quot;Downloads Complete&quot; PopUp? 的本地化字符串。
        /// </summary>
        internal static string chbShowDCPopUps {
            get {
                return ResourceManager.GetString("chbShowDCPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Tray PopUps 的本地化字符串。
        /// </summary>
        internal static string chbShowPopUps {
            get {
                return ResourceManager.GetString("chbShowPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download each Thread in its own folder 的本地化字符串。
        /// </summary>
        internal static string chbSubdirectories {
            get {
                return ResourceManager.GetString("chbSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download each Post in its own folder 的本地化字符串。
        /// </summary>
        internal static string chbSubThreadRip {
            get {
                return ResourceManager.GetString("chbSubThreadRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember Me 的本地化字符串。
        /// </summary>
        internal static string chRememberCred {
            get {
                return ResourceManager.GetString("chRememberCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard Monitoring 的本地化字符串。
        /// </summary>
        internal static string clipboardWatch {
            get {
                return ResourceManager.GetString("clipboardWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Ripper 的本地化字符串。
        /// </summary>
        internal static string CloseRipper {
            get {
                return ResourceManager.GetString("CloseRipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap cn {
            get {
                object obj = ResourceManager.GetObject("cn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Extracting 的本地化字符串。
        /// </summary>
        internal static string CurrentlyExtract {
            get {
                return ResourceManager.GetString("CurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap de {
            get {
                object obj = ResourceManager.GetObject("de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Do Nothing 的本地化字符串。
        /// </summary>
        internal static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Options 的本地化字符串。
        /// </summary>
        internal static string downloadOptions {
            get {
                return ResourceManager.GetString("downloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap fr {
            get {
                object obj = ResourceManager.GetObject("fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Currently, 的本地化字符串。
        /// </summary>
        internal static string gbCurrently {
            get {
                return ResourceManager.GetString("gbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently, System is waiting for threads to exit... 的本地化字符串。
        /// </summary>
        internal static string gbCurrentlyExit {
            get {
                return ResourceManager.GetString("gbCurrentlyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently, System is extracting 的本地化字符串。
        /// </summary>
        internal static string gbCurrentlyExtract {
            get {
                return ResourceManager.GetString("gbCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently, System is idling... 的本地化字符串。
        /// </summary>
        internal static string gbCurrentlyIdle {
            get {
                return ResourceManager.GetString("gbCurrentlyIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Or Login as Guest ... 的本地化字符串。
        /// </summary>
        internal static string gbGuestLoginHead {
            get {
                return ResourceManager.GetString("gbGuestLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Language 的本地化字符串。
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Provide Login Credentials to the Forums 的本地化字符串。
        /// </summary>
        internal static string gbLoginHead {
            get {
                return ResourceManager.GetString("gbLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Options 的本地化字符串。
        /// </summary>
        internal static string gbMainOptions {
            get {
                return ResourceManager.GetString("gbMainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing Cached Thread XML... 的本地化字符串。
        /// </summary>
        internal static string gbParse {
            get {
                return ResourceManager.GetString("gbParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing jobs.xml... 的本地化字符串。
        /// </summary>
        internal static string gbParse2 {
            get {
                return ResourceManager.GetString("gbParse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Guest Login 的本地化字符串。
        /// </summary>
        internal static string guestLoginButton {
            get {
                return ResourceManager.GetString("guestLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Guest Mode] 的本地化字符串。
        /// </summary>
        internal static string guestModeText {
            get {
                return ResourceManager.GetString("guestModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download Folder : 的本地化字符串。
        /// </summary>
        internal static string lblDownloadFolder {
            get {
                return ResourceManager.GetString("lblDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading: 0 of 0 的本地化字符串。
        /// </summary>
        internal static string lblDownloading {
            get {
                return ResourceManager.GetString("lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Downloading: {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string lblDownloadingof {
            get {
                return ResourceManager.GetString("lblDownloadingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login FAILED! 的本地化字符串。
        /// </summary>
        internal static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Picture Downloaded: 的本地化字符串。
        /// </summary>
        internal static string lblLastPicture {
            get {
                return ResourceManager.GetString("lblLastPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min. Image Count to give Thanks: 的本地化字符串。
        /// </summary>
        internal static string lblminImageCount {
            get {
                return ResourceManager.GetString("lblminImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password : 的本地化字符串。
        /// </summary>
        internal static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ripping Queue 的本地化字符串。
        /// </summary>
        internal static string lblRippingQue {
            get {
                return ResourceManager.GetString("lblRippingQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Waiting for the Forum... 的本地化字符串。
        /// </summary>
        internal static string lblStatWait {
            get {
                return ResourceManager.GetString("lblStatWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum Simultaneous Downloads: 的本地化字符串。
        /// </summary>
        internal static string lblThreadLimit {
            get {
                return ResourceManager.GetString("lblThreadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Threads: {0} of {1} 的本地化字符串。
        /// </summary>
        internal static string lblThreads {
            get {
                return ResourceManager.GetString("lblThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Threads: 0 of  的本地化字符串。
        /// </summary>
        internal static string lblThreads2 {
            get {
                return ResourceManager.GetString("lblThreads2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name : 的本地化字符串。
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WARNING! More than 5 failed tries will result in your Account being locked! You have been warned! 的本地化字符串。
        /// </summary>
        internal static string lblWarningLogin {
            get {
                return ResourceManager.GetString("lblWarningLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome,  的本地化字符串。
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string logintext {
            get {
                return ResourceManager.GetString("logintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Post already ripped, do you want to rip it again? 的本地化字符串。
        /// </summary>
        internal static string mBAlready {
            get {
                return ResourceManager.GetString("mBAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 That Thread or Post is Already Queued. 的本地化字符串。
        /// </summary>
        internal static string mbAlreadyQueued {
            get {
                return ResourceManager.GetString("mbAlreadyQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to close Ripper now? 的本地化字符串。
        /// </summary>
        internal static string mbExit {
            get {
                return ResourceManager.GetString("mbExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Ripper 的本地化字符串。
        /// </summary>
        internal static string mbExitTtl {
            get {
                return ResourceManager.GetString("mbExitTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You entered an incorrect URL. 的本地化字符串。
        /// </summary>
        internal static string mbIncorrectURL {
            get {
                return ResourceManager.GetString("mbIncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid Destination Path! Please set up the Download Folder first. 的本地化字符串。
        /// </summary>
        internal static string mbInvalidDes {
            get {
                return ResourceManager.GetString("mbInvalidDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such post exists! 的本地化字符串。
        /// </summary>
        internal static string mbNoPost {
            get {
                return ResourceManager.GetString("mbNoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such thread exists! 的本地化字符串。
        /// </summary>
        internal static string mbNoThread {
            get {
                return ResourceManager.GetString("mbNoThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit MUST be between 1 and 20! 的本地化字符串。
        /// </summary>
        internal static string mbThreadbetw {
            get {
                return ResourceManager.GetString("mbThreadbetw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit MUST be numeric! 的本地化字符串。
        /// </summary>
        internal static string mbThreadNum {
            get {
                return ResourceManager.GetString("mbThreadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID MUST be numeric! 的本地化字符串。
        /// </summary>
        internal static string mbTNumeric {
            get {
                return ResourceManager.GetString("mbTNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A new version of VG-Ripper is available. Would You like to upgrade? 的本地化字符串。
        /// </summary>
        internal static string mbUpdate {
            get {
                return ResourceManager.GetString("mbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Version Available! 的本地化字符串。
        /// </summary>
        internal static string mbUpdate2 {
            get {
                return ResourceManager.GetString("mbUpdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close Program 的本地化字符串。
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Ripping Queue 的本地化字符串。
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options 的本地化字符串。
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Image Hosts Plugin will be automatically updated now and Ripper will restart! 的本地化字符串。
        /// </summary>
        internal static string ServicesUpdate {
            get {
                return ResourceManager.GetString("ServicesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show Last Download Image 的本地化字符串。
        /// </summary>
        internal static string ShowLastDownloaded {
            get {
                return ResourceManager.GetString("ShowLastDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning! DO NOT close application, waiting for downloads to finish... 的本地化字符串。
        /// </summary>
        internal static string StatusLabelInfo {
            get {
                return ResourceManager.GetString("StatusLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Images remaining (Total Downloaded: {1}%) 的本地化字符串。
        /// </summary>
        internal static string tiImagesRemain {
            get {
                return ResourceManager.GetString("tiImagesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VG-Ripper Downloading ... 的本地化字符串。
        /// </summary>
        internal static string tthisText {
            get {
                return ResourceManager.GetString("tthisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  [Logged in as: &quot; 的本地化字符串。
        /// </summary>
        internal static string ttlHeader {
            get {
                return ResourceManager.GetString("ttlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap us {
            get {
                object obj = ResourceManager.GetObject("us", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
