//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripper.Languages {
    using System;
    using System.Globalization;
    using System.Resources;

    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute(
        "System.Resources.Tools.StronglyTypedResourceBuilder",
        "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class french
    {
        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(
            "Microsoft.Performance",
            "CA1811:AvoidUncalledPrivateCode")]
        internal french()
        {
        }

        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new global::System.Resources.ResourceManager(
                        "Ripper.Languages.french",
                        typeof(french).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(
            global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add New Forum Account ähnelt.
        /// </summary>
        internal static string AddNewAccount
        {
            get
            {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After Download(s) finished... ähnelt.
        /// </summary>
        internal static string AfterDownload
        {
            get
            {
                return ResourceManager.GetString("AfterDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraction en cours... ähnelt.
        /// </summary>
        internal static string bSystemExtr
        {
            get
            {
                return ResourceManager.GetString("bSystemExtr", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PG-Ripper a fini tout Télécharge ähnelt.
        /// </summary>
        internal static string btexExit
        {
            get
            {
                return ResourceManager.GetString("btexExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharge complet ähnelt.
        /// </summary>
        internal static string btleExit
        {
            get
            {
                return ResourceManager.GetString("btleExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die En attente ähnelt.
        /// </summary>
        internal static string btleIdle
        {
            get
            {
                return ResourceManager.GetString("btleIdle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appliquer ähnelt.
        /// </summary>
        internal static string btnApply
        {
            get
            {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parcourir ähnelt.
        /// </summary>
        internal static string btnBrowse
        {
            get
            {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fermer ähnelt.
        /// </summary>
        internal static string btnClose
        {
            get
            {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ouvrez un classeur ähnelt.
        /// </summary>
        internal static string btnOpenFolder
        {
            get
            {
                return ResourceManager.GetString("btnOpenFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharger ähnelt.
        /// </summary>
        internal static string btnStartDownload
        {
            get
            {
                return ResourceManager.GetString("btnStartDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arreter le téléchargement ähnelt.
        /// </summary>
        internal static string btnStop
        {
            get
            {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Toujours en haut ähnelt.
        /// </summary>
        internal static string chbAlwaysOnTop
        {
            get
            {
                return ResourceManager.GetString("chbAlwaysOnTop", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Demandez Télécharger le Classeur avant Téléchargement ähnelt.
        /// </summary>
        internal static string chbAskDownloadFolder
        {
            get
            {
                return ResourceManager.GetString("chbAskDownloadFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remercier automatiquement ähnelt.
        /// </summary>
        internal static string chbAutoTKButton
        {
            get
            {
                return ResourceManager.GetString("chbAutoTKButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die L&apos;économie a Déchiré des poteaux pour vérifier ähnelt.
        /// </summary>
        internal static string chbSaveHistory
        {
            get
            {
                return ResourceManager.GetString("chbSaveHistory", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Est-ce que le spectacle télécharge PopUp complet? ähnelt.
        /// </summary>
        internal static string chbShowDCPopUps
        {
            get
            {
                return ResourceManager.GetString("chbShowDCPopUps", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voir Les PopUps ähnelt.
        /// </summary>
        internal static string chbShowPopUps
        {
            get
            {
                return ResourceManager.GetString("chbShowPopUps", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharger chaque fil dans son propre dossier ähnelt.
        /// </summary>
        internal static string chbSubdirectories
        {
            get
            {
                return ResourceManager.GetString("chbSubdirectories", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharger chaque poste dans son propre dossier ähnelt.
        /// </summary>
        internal static string chbSubThreadRip
        {
            get
            {
                return ResourceManager.GetString("chbSubThreadRip", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Se souvenir de moi ähnelt.
        /// </summary>
        internal static string chRememberCred
        {
            get
            {
                return ResourceManager.GetString("chRememberCred", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clipboard Monitoring ähnelt.
        /// </summary>
        internal static string clipboardWatch
        {
            get
            {
                return ResourceManager.GetString("clipboardWatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Ripper ähnelt.
        /// </summary>
        internal static string CloseRipper
        {
            get
            {
                return ResourceManager.GetString("CloseRipper", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extraction ähnelt.
        /// </summary>
        internal static string CurrentlyExtract
        {
            get
            {
                return ResourceManager.GetString("CurrentlyExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supprimer compte sur le forum ähnelt.
        /// </summary>
        internal static string DeleteAccount
        {
            get
            {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do Nothing ähnelt.
        /// </summary>
        internal static string DoNothing
        {
            get
            {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options de Téléchargement ähnelt.
        /// </summary>
        internal static string downloadOptions
        {
            get
            {
                return ResourceManager.GetString("downloadOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die En cours, ähnelt.
        /// </summary>
        internal static string gbCurrently
        {
            get
            {
                return ResourceManager.GetString("gbCurrently", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actuellement, le système de J&apos;attends l&apos;arrêt de threads ähnelt.
        /// </summary>
        internal static string gbCurrentlyExit
        {
            get
            {
                return ResourceManager.GetString("gbCurrentlyExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actuellement, En train d&apos;extraire ähnelt.
        /// </summary>
        internal static string gbCurrentlyExtract
        {
            get
            {
                return ResourceManager.GetString("gbCurrentlyExtract", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actuellement, En attente... ähnelt.
        /// </summary>
        internal static string gbCurrentlyIdle
        {
            get
            {
                return ResourceManager.GetString("gbCurrentlyIdle", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choisir Langue ähnelt.
        /// </summary>
        internal static string gbLanguage
        {
            get
            {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entrez vos identifiants ähnelt.
        /// </summary>
        internal static string gbLoginHead
        {
            get
            {
                return ResourceManager.GetString("gbLoginHead", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options Principales ähnelt.
        /// </summary>
        internal static string gbMainOptions
        {
            get
            {
                return ResourceManager.GetString("gbMainOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyse de la page... ähnelt.
        /// </summary>
        internal static string gbParse
        {
            get
            {
                return ResourceManager.GetString("gbParse", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analyse de la jobs.xml... ähnelt.
        /// </summary>
        internal static string gbParse2
        {
            get
            {
                return ResourceManager.GetString("gbParse2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die l&apos;accès des clients ähnelt.
        /// </summary>
        internal static string GuestLogin
        {
            get
            {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Répertoire de téléchargement : ähnelt.
        /// </summary>
        internal static string lblDownloadFolder
        {
            get
            {
                return ResourceManager.GetString("lblDownloadFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharge: 0 sur 0 ähnelt.
        /// </summary>
        internal static string lblDownloading
        {
            get
            {
                return ResourceManager.GetString("lblDownloading", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Télécharge: {0} sur {1} ähnelt.
        /// </summary>
        internal static string lblDownloadingof
        {
            get
            {
                return ResourceManager.GetString("lblDownloadingof", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification ECHOUEE! ähnelt.
        /// </summary>
        internal static string lblFailed
        {
            get
            {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forum: ähnelt.
        /// </summary>
        internal static string lblForums
        {
            get
            {
                return ResourceManager.GetString("lblForums", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Derniére image téléchargée: ähnelt.
        /// </summary>
        internal static string lblLastPicture
        {
            get
            {
                return ResourceManager.GetString("lblLastPicture", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. Compte de l&apos;image donner Merci: ähnelt.
        /// </summary>
        internal static string lblminImageCount
        {
            get
            {
                return ResourceManager.GetString("lblminImageCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mot de passe : ähnelt.
        /// </summary>
        internal static string lblPass
        {
            get
            {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File d&apos;attente ähnelt.
        /// </summary>
        internal static string lblRippingQue
        {
            get
            {
                return ResourceManager.GetString("lblRippingQue", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attente de la réponse... ähnelt.
        /// </summary>
        internal static string lblStatWait
        {
            get
            {
                return ResourceManager.GetString("lblStatWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximal simultanés downloads: ähnelt.
        /// </summary>
        internal static string lblThreadLimit
        {
            get
            {
                return ResourceManager.GetString("lblThreadLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processus: {0} sur {1} ähnelt.
        /// </summary>
        internal static string lblThreads
        {
            get
            {
                return ResourceManager.GetString("lblThreads", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processus: 0 sur  ähnelt.
        /// </summary>
        internal static string lblThreads2
        {
            get
            {
                return ResourceManager.GetString("lblThreads2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Utilisateur : ähnelt.
        /// </summary>
        internal static string lblUser
        {
            get
            {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ATTENTION: Au bout de 3 tentatives infructueuse votre compte serra bloqué! Vous étes PREVENUS! ähnelt.
        /// </summary>
        internal static string lblWarningLogin
        {
            get
            {
                return ResourceManager.GetString("lblWarningLogin", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bienvenue,  ähnelt.
        /// </summary>
        internal static string lblWelcome
        {
            get
            {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Identification ähnelt.
        /// </summary>
        internal static string logintext
        {
            get
            {
                return ResourceManager.GetString("logintext", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Post déjà déchirée, voulez-vous déchirer de nouveau? ähnelt.
        /// </summary>
        internal static string mBAlready
        {
            get
            {
                return ResourceManager.GetString("mBAlready", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Déja dans la file d&apos;attente ähnelt.
        /// </summary>
        internal static string mbAlreadyQueued
        {
            get
            {
                return ResourceManager.GetString("mbAlreadyQueued", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voulez-vous fermer Ripper maintenant? ähnelt.
        /// </summary>
        internal static string mbExit
        {
            get
            {
                return ResourceManager.GetString("mbExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fermer Ripper ähnelt.
        /// </summary>
        internal static string mbExitTtl
        {
            get
            {
                return ResourceManager.GetString("mbExitTtl", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lien Incorrect. ähnelt.
        /// </summary>
        internal static string mbIncorrectURL
        {
            get
            {
                return ResourceManager.GetString("mbIncorrectURL", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destination Invalide! ähnelt.
        /// </summary>
        internal static string mbInvalidDes
        {
            get
            {
                return ResourceManager.GetString("mbInvalidDes", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N&apos;existe pas! ähnelt.
        /// </summary>
        internal static string mbNoPost
        {
            get
            {
                return ResourceManager.GetString("mbNoPost", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die N&apos;existe pas! ähnelt.
        /// </summary>
        internal static string mbNoThread
        {
            get
            {
                return ResourceManager.GetString("mbNoThread", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La limite de processus doit étre entre 1 et 20! ähnelt.
        /// </summary>
        internal static string mbThreadbetw
        {
            get
            {
                return ResourceManager.GetString("mbThreadbetw", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die La limite de processus doit étre numerique! ähnelt.
        /// </summary>
        internal static string mbThreadNum
        {
            get
            {
                return ResourceManager.GetString("mbThreadNum", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doit étre numérique! ähnelt.
        /// </summary>
        internal static string mbTNumeric
        {
            get
            {
                return ResourceManager.GetString("mbTNumeric", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Une nouvelle version d&apos;Éventreur est disponible. Aimeriez-Vous améliorer? ähnelt.
        /// </summary>
        internal static string mbUpdate
        {
            get
            {
                return ResourceManager.GetString("mbUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nouvelle Version disponible! ähnelt.
        /// </summary>
        internal static string mbUpdate2
        {
            get
            {
                return ResourceManager.GetString("mbUpdate2", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string MenuAbout
        {
            get
            {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Comptes ähnelt.
        /// </summary>
        internal static string MenuAccounts
        {
            get
            {
                return ResourceManager.GetString("MenuAccounts", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fermer ähnelt.
        /// </summary>
        internal static string MenuExit
        {
            get
            {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Ripping Queue ähnelt.
        /// </summary>
        internal static string MenuExport
        {
            get
            {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        internal static string MenuFile
        {
            get
            {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aider ähnelt.
        /// </summary>
        internal static string MenuHelp
        {
            get
            {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string MenuOptions
        {
            get
            {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Options ähnelt.
        /// </summary>
        internal static string MenuSettings
        {
            get
            {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Hosts Plugin will be automatically updated now and Ripper will restart! ähnelt.
        /// </summary>
        internal static string ServicesUpdate
        {
            get
            {
                return ResourceManager.GetString("ServicesUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show last download image ähnelt.
        /// </summary>
        internal static string ShowLastDownloaded
        {
            get
            {
                return ResourceManager.GetString("ShowLastDownloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attention! Attendre la fin des téléchargements ... ähnelt.
        /// </summary>
        internal static string StatusLabelInfo
        {
            get
            {
                return ResourceManager.GetString("StatusLabelInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Images restantes (Total Téléchargé: {1}%) ähnelt.
        /// </summary>
        internal static string tiImagesRemain
        {
            get
            {
                return ResourceManager.GetString("tiImagesRemain", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PG-Ripper Télécharge ... ähnelt.
        /// </summary>
        internal static string tthisText
        {
            get
            {
                return ResourceManager.GetString("tthisText", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  [Identifié comme: &quot; ähnelt.
        /// </summary>
        internal static string ttlHeader
        {
            get
            {
                return ResourceManager.GetString("ttlHeader", resourceCulture);
            }
        }
    }
}
