//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ripper.Languages {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class german {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal german() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ripper.Languages.german", typeof(german).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Foren Konto hinzufügen ähnelt.
        /// </summary>
        internal static string AddNewAccount {
            get {
                return ResourceManager.GetString("AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wenn alle Download(s) beendet sind... ähnelt.
        /// </summary>
        internal static string AfterDownload {
            get {
                return ResourceManager.GetString("AfterDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System extrahiert... ähnelt.
        /// </summary>
        internal static string bSystemExtr {
            get {
                return ResourceManager.GetString("bSystemExtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PG-Ripper hat alle Downloads abgeschlossen ähnelt.
        /// </summary>
        internal static string btexExit {
            get {
                return ResourceManager.GetString("btexExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Downloads abgeschlossen ähnelt.
        /// </summary>
        internal static string btleExit {
            get {
                return ResourceManager.GetString("btleExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das System faulenzt ähnelt.
        /// </summary>
        internal static string btleIdle {
            get {
                return ResourceManager.GetString("btleIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übernehmen ähnelt.
        /// </summary>
        internal static string btnApply {
            get {
                return ResourceManager.GetString("btnApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse ähnelt.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string btnClose {
            get {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ordner öffen ähnelt.
        /// </summary>
        internal static string btnOpenFolder {
            get {
                return ResourceManager.GetString("btnOpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte Download ähnelt.
        /// </summary>
        internal static string btnStartDownload {
            get {
                return ResourceManager.GetString("btnStartDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job stoppen/löschen ähnelt.
        /// </summary>
        internal static string btnStop {
            get {
                return ResourceManager.GetString("btnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrahierung ähnelt.
        /// </summary>
        internal static string bttleCurrentlyExtract {
            get {
                return ResourceManager.GetString("bttleCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fenster immer im Vordergrund ähnelt.
        /// </summary>
        internal static string chbAlwaysOnTop {
            get {
                return ResourceManager.GetString("chbAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach Download Ordner fragen bevor der Download startet ähnelt.
        /// </summary>
        internal static string chbAskDownloadFolder {
            get {
                return ResourceManager.GetString("chbAskDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatisch den &quot;Thank You&quot; Button drücken ähnelt.
        /// </summary>
        internal static string chbAutoTKButton {
            get {
                return ResourceManager.GetString("chbAutoTKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerippte Beiträge speichern zum checken ähnelt.
        /// </summary>
        internal static string chbSaveHistory {
            get {
                return ResourceManager.GetString("chbSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige &quot;Downloads abgeschlossen&quot; PopUp? ähnelt.
        /// </summary>
        internal static string chbShowDCPopUps {
            get {
                return ResourceManager.GetString("chbShowDCPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tray PopUps benutzen ähnelt.
        /// </summary>
        internal static string chbShowPopUps {
            get {
                return ResourceManager.GetString("chbShowPopUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Themen in Unterverzeichnisse herunterladen ähnelt.
        /// </summary>
        internal static string chbSubdirectories {
            get {
                return ResourceManager.GetString("chbSubdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beiträge in Unterverzeichnisse herunterladen ähnelt.
        /// </summary>
        internal static string chbSubThreadRip {
            get {
                return ResourceManager.GetString("chbSubThreadRip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung speichern ähnelt.
        /// </summary>
        internal static string chRememberCred {
            get {
                return ResourceManager.GetString("chRememberCred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zwischenablage überwachen ähnelt.
        /// </summary>
        internal static string clipboardWatch {
            get {
                return ResourceManager.GetString("clipboardWatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ripper Schließen ähnelt.
        /// </summary>
        internal static string CloseRipper {
            get {
                return ResourceManager.GetString("CloseRipper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forum Konto löschen ähnelt.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nichts tun ähnelt.
        /// </summary>
        internal static string DoNothing {
            get {
                return ResourceManager.GetString("DoNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Optionen ähnelt.
        /// </summary>
        internal static string downloadOptions {
            get {
                return ResourceManager.GetString("downloadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell, ähnelt.
        /// </summary>
        internal static string gbCurrently {
            get {
                return ResourceManager.GetString("gbCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell, Wartet das System auf das Beenden von Threads... ähnelt.
        /// </summary>
        internal static string gbCurrentlyExit {
            get {
                return ResourceManager.GetString("gbCurrentlyExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell, extrahiert das System ähnelt.
        /// </summary>
        internal static string gbCurrentlyExtract {
            get {
                return ResourceManager.GetString("gbCurrentlyExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktuell, faulenzt das System... ähnelt.
        /// </summary>
        internal static string gbCurrentlyIdle {
            get {
                return ResourceManager.GetString("gbCurrentlyIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprachauswahl ähnelt.
        /// </summary>
        internal static string gbLanguage {
            get {
                return ResourceManager.GetString("gbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geben Sie ihere Zugangsdaten aus dem Forum ein ähnelt.
        /// </summary>
        internal static string gbLoginHead {
            get {
                return ResourceManager.GetString("gbLoginHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programm Optionen ähnelt.
        /// </summary>
        internal static string gbMainOptions {
            get {
                return ResourceManager.GetString("gbMainOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysiert das gecachte HTML... ähnelt.
        /// </summary>
        internal static string gbParse {
            get {
                return ResourceManager.GetString("gbParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Analysiert die jobs.xml... ähnelt.
        /// </summary>
        internal static string gbParse2 {
            get {
                return ResourceManager.GetString("gbParse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gastzugang ähnelt.
        /// </summary>
        internal static string GuestLogin {
            get {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Ordner : ähnelt.
        /// </summary>
        internal static string lblDownloadFolder {
            get {
                return ResourceManager.GetString("lblDownloadFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lädt: 0 von 0 ähnelt.
        /// </summary>
        internal static string lblDownloading {
            get {
                return ResourceManager.GetString("lblDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lädt: {0} von {1} ähnelt.
        /// </summary>
        internal static string lblDownloadingof {
            get {
                return ResourceManager.GetString("lblDownloadingof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmeldung FEHLGESCHLAGEN! ähnelt.
        /// </summary>
        internal static string lblFailed {
            get {
                return ResourceManager.GetString("lblFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forumauswahl: ähnelt.
        /// </summary>
        internal static string lblForums {
            get {
                return ResourceManager.GetString("lblForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt heruntergeladenens Bild: ähnelt.
        /// </summary>
        internal static string lblLastPicture {
            get {
                return ResourceManager.GetString("lblLastPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Min. Anzahl an Bildern für Thanks: ähnelt.
        /// </summary>
        internal static string lblminImageCount {
            get {
                return ResourceManager.GetString("lblminImageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passwort : ähnelt.
        /// </summary>
        internal static string lblPass {
            get {
                return ResourceManager.GetString("lblPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausstehende Jobs ähnelt.
        /// </summary>
        internal static string lblRippingQue {
            get {
                return ResourceManager.GetString("lblRippingQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warte auf Forum... ähnelt.
        /// </summary>
        internal static string lblStatWait {
            get {
                return ResourceManager.GetString("lblStatWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximale Gleichzeitige Downloads: ähnelt.
        /// </summary>
        internal static string lblThreadLimit {
            get {
                return ResourceManager.GetString("lblThreadLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads: {0} von {1} ähnelt.
        /// </summary>
        internal static string lblThreads {
            get {
                return ResourceManager.GetString("lblThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads: 0 von  ähnelt.
        /// </summary>
        internal static string lblThreads2 {
            get {
                return ResourceManager.GetString("lblThreads2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benutzername : ähnelt.
        /// </summary>
        internal static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die WARNUNG! Mehr als 3 fehlgeschlagenden versuche, und ihr Account wird gesperrt! Sie wurden also gewarnt! ähnelt.
        /// </summary>
        internal static string lblWarningLogin {
            get {
                return ResourceManager.GetString("lblWarningLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen,  ähnelt.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anmelden ähnelt.
        /// </summary>
        internal static string logintext {
            get {
                return ResourceManager.GetString("logintext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beitag wurde bereits gerippet, Wollen Sie den Beitrag erneut rippen? ähnelt.
        /// </summary>
        internal static string mBAlready {
            get {
                return ResourceManager.GetString("mBAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Thema oder Beitrag wird bereits geladen!RIP ähnelt.
        /// </summary>
        internal static string mbAlreadyQueued {
            get {
                return ResourceManager.GetString("mbAlreadyQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wollen Sie den Ripper beenden? ähnelt.
        /// </summary>
        internal static string mbExit {
            get {
                return ResourceManager.GetString("mbExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close Ripper ähnelt.
        /// </summary>
        internal static string mbExitTtl {
            get {
                return ResourceManager.GetString("mbExitTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie haben eine ungültige URL eingegeben!. ähnelt.
        /// </summary>
        internal static string mbIncorrectURL {
            get {
                return ResourceManager.GetString("mbIncorrectURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ungültiges Ziel Verzeichnis! Bitte geben Sie zuerst ein Download Verzeichnis an! ähnelt.
        /// </summary>
        internal static string mbInvalidDes {
            get {
                return ResourceManager.GetString("mbInvalidDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieser Beitrag exestiert nicht! ähnelt.
        /// </summary>
        internal static string mbNoPost {
            get {
                return ResourceManager.GetString("mbNoPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Thema exestiert nicht! ähnelt.
        /// </summary>
        internal static string mbNoThread {
            get {
                return ResourceManager.GetString("mbNoThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit MUSS zwischen 1 und 20 liegen! ähnelt.
        /// </summary>
        internal static string mbThreadbetw {
            get {
                return ResourceManager.GetString("mbThreadbetw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Limit MUSS numerisch sein! ähnelt.
        /// </summary>
        internal static string mbThreadNum {
            get {
                return ResourceManager.GetString("mbThreadNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID MUSS eine Nummer sein! ähnelt.
        /// </summary>
        internal static string mbTNumeric {
            get {
                return ResourceManager.GetString("mbTNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Eine neue Version vom Ripper ist verfügbar. Möchten Sie das Programm aktualisieren? ähnelt.
        /// </summary>
        internal static string mbUpdate {
            get {
                return ResourceManager.GetString("mbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neue Version ist verfügbar! ähnelt.
        /// </summary>
        internal static string mbUpdate2 {
            get {
                return ResourceManager.GetString("mbUpdate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Über ähnelt.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Konten ähnelt.
        /// </summary>
        internal static string MenuAccounts {
            get {
                return ResourceManager.GetString("MenuAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Ripping Queue ähnelt.
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datei ähnelt.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Optionen ähnelt.
        /// </summary>
        internal static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Image Hosts Plugin will be automatically updated now and Ripper will restart! ähnelt.
        /// </summary>
        internal static string ServicesUpdate {
            get {
                return ResourceManager.GetString("ServicesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zuletzt heruntergeladenes Bild anzeigen ähnelt.
        /// </summary>
        internal static string ShowLastDownloaded {
            get {
                return ResourceManager.GetString("ShowLastDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning! Warte auf das beenden von Downloads... ähnelt.
        /// </summary>
        internal static string StatusLabelInfo {
            get {
                return ResourceManager.GetString("StatusLabelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} Bilder verbleiben (Insgesamt geladen: {1}%)  ähnelt.
        /// </summary>
        internal static string tiImagesRemain {
            get {
                return ResourceManager.GetString("tiImagesRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PG-Ripper lädt ... ähnelt.
        /// </summary>
        internal static string tthisText {
            get {
                return ResourceManager.GetString("tthisText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  [Angemeldet als: &quot; ähnelt.
        /// </summary>
        internal static string ttlHeader {
            get {
                return ResourceManager.GetString("ttlHeader", resourceCulture);
            }
        }
    }
}
